Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -5,6 +5,11 @@ on:
 #    - cron: "0 * * * *"  # Runs every hour
   workflow_dispatch:
     inputs:
+      publish_version:
+        description: 'Do you want to publish the version on web?'
+        required: true
+        default: 'false'
+        type: boolean
       build_tag:
         description: 'A tag of the Namadillo source to use (otherwise latest is used)'
         default: ''
@@ -91,7 +96,6 @@ jobs:
           echo switching to $LATEST_TAG for the build process 
           git checkout $LATEST_TAG
       - name: Restore yarn cache
-        if: env.do_build == 'true'
         uses: actions/cache@v3
         with:
           path: |
@@ -111,7 +115,6 @@ jobs:
           shared-key: ${{ inputs.cache-name }}
 
       - name: Install dependencies
-        if: env.do_build == 'true'
         run: yarn
         shell: bash
         working-directory: source-repo
@@ -120,30 +123,25 @@ jobs:
         run: rustup toolchain add nightly-2025-03-27
 
       - name: Install protoc
-        if: env.do_build == 'true'
         run: sudo apt-get install -y protobuf-compiler
 
       - name: Build Namadillo
-        if: env.do_build == 'true'
         working-directory: source-repo/apps/namadillo
         run: yarn build
 
       - name: Build the Chrome extension
-        if: env.do_build == 'true'
         working-directory: source-repo/apps/extension
         run: yarn build:chrome
         env:
             NAMADA_INTERFACE_NAMADA_CHAIN_ID: ${{ env.CHAIN_ID }}
 
       - name: Build the Firefox extension
-        if: env.do_build == 'true'
         working-directory: source-repo/apps/extension
         run: yarn build:firefox
         env:
             NAMADA_INTERFACE_NAMADA_CHAIN_ID: ${{ env.CHAIN_ID }}
 
       - name: Copy the extensions for deployment
-        if: env.do_build == 'true'
         run: |
             cp source-repo/apps/extension/build/firefox/namada_keychain-*.zip source-repo/apps/namadillo/dist/namada-keychain-firefox.zip
             cp source-repo/apps/extension/build/chrome/namada_keychain-*.zip source-repo/apps/namadillo/dist/namada-keychain-chrome.zip
@@ -195,7 +193,6 @@ jobs:
 
 
       - name: Configure Namadillo
-        if: env.do_build == 'true'
         working-directory: source-repo/apps/namadillo
         run: |
             echo "" > dist/config.toml
@@ -204,10 +201,35 @@ jobs:
             echo "masp_indexer_url = \"${{ env.MASP_URL }}\"" >> dist/config.toml
 
       - name: Clone Target repository
-        if: env.do_build == 'true'
         uses: actions/checkout@v4
         with:
           repository: shield-crypto/namadillo-build
           ref: main
           path: target-repo
           ssh-key: ${{ secrets.GH_DEPLOY_KEY }}
+
+      - name: Publish site
+        if: ${{ github.event.inputs.publish_version == 'true' }}
+        run: |
+            ls source-repo
+            ls target-repo
+            cd target-repo
+            git config --global user.name "GitHub Actions"
+            git config --global user.email "actions@github.com"
+            echo clean up existing site
+            rm -rf *
+            git rm -r . || true  # Ignore if there is nothing to remove
+            git commit -m "docs: Cleanup old version" || true # Prevent failure if nothing changed
+            echo copying the new site
+            cp -r ../source-repo/apps/namadillo/dist/* .
+            git add .
+            git commit -m "docs: Deploy version"
+            git push origin main
+
+      - name: Save last processed tag
+        run: |
+            git config --global user.name "GitHub Actions"
+            git config --global user.email "actions@github.com"
+            git add .github/last_tag.txt
+            git commit -m "chore: update last built tag"
+            git push origin main
